# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XT1FTObimWAE8rMuO03fLRqgJJzpRcxa
"""

import pandas as pd
df=pd.DataFrame({"a":[4,5,6],"b":[7,8,9],"c":[10,11,12]},index=[1,2,3])
print(df)

import pandas as pd
dt=[1,2,3,4]
df=pd.DataFrame(dt)
print(df)

import pandas as pd
data=[['Alex',10],['Bob',12]]
df=pd.DataFrame(data,columns=['name','age'],index=['a1','b2'])
print(df)

import pandas as pd
data={'cars':["BMW","Volvo","Ford"],'passings':[3,7,2]}
vr=pd.DataFrame(data)
print(vr)

import pandas as pd
data=[{'a':1,'b':2},{'a':5,'b':10,'c':20}]
df=pd.DataFrame(data)
print(df)
df=pd.DataFrame(data,index=['first','second'])
print(df)
df1=pd.DataFrame(data,index=['first','second'],columns=['a','b'])
print(df1)

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Height':[5.3,6.2,5.0,5.8],'Qualification':['Msc','MA','Msc','Msc']}
df=pd.DataFrame(data)
add=['delhi','Bengalore','Chennai','patna']
df['Address']=add
print(df)

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Height':[5.3,6.2,5.0,5.8],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
del df['add']
df

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Height':[5.3,6.2,5.0,5.8],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df.drop(['add'],axis=1,inplace=True)
df

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Height':[5.3,6.2,5.0,5.8],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df.pop('add')
df.pop('Height')
df

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,24,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
print(df)
df.rename(columns={'add':'City'},inplace=True)
df

import pandas as pd
df=pd.DataFrame([[1,2],[3,4]],columns=['a','b'])
df2=pd.DataFrame([[5,6],[7,8]],columns=['a','b'])
df=pd.concat([df,df2])
df

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,24,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
print(df)
df.drop(2,axis=0,inplace=True)
df

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,24,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df=df['Name']
print(df)

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,24,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
print(df[['Name','Qualification']])

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,24,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df.filter(items=['Name','Age'])

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,24,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df.filter(like='ge')

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,24,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df.filter(regex='g|f',axis=1)

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df=df.drop_duplicates(subset=['Qualification'])
df

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df=df.drop_duplicates(subset=['Qualification'],keep='last')
df

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
dfs=df.sample(n=2)
print(dfs)

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
dfs=df.sample(frac=.5)
print(dfs)

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
tops=df.nlargest(2,columns='Age')
print(tops)

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
tops=df.nsmallest(2,columns='Age')
print(tops)

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df=df.query('Age>=30')
print(df)

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df=df.query('Name.str.contains("i") and Age > 25')
print(df)

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df=df.query('Qualification == ["Msc" , "MA"] and Age<25')
print(df)

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df.loc[:,'Age']

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df.loc[:,['Name','Age']]

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df.iloc[:,3]

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df_fil=df[(df['Qualification']=='Msc')&(df['Age']>22)]
print(df_fil)

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df_fil=df[(df['Name'].str.startswith('A','C'))]
print(df_fil)

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
print(df.tail(3))

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
df.info()

import pandas as pd
data={'Name':['Jai','Jeeva','Jaydeep','Jeyan'],'Age':[27,22,22,32],'Qualification':['Msc','MA','Msc','Msc'],'add':['delhi','Bengalore','Chennai','patna']}
df=pd.DataFrame(data)
gro=df.groupby('Qualification').mean()['Age']
print(gro)

import pandas as pd
data={'name':{'Alice','Bob','Charlie','Dave','Emily','Frank'},'gender':{'F','M','M','M','F','M'},'age':[25,35,40,28,30,45],'salary':[50000,70000,60000,80000,65000,90000]}
df=pd.DataFrame(data)
groped=df.groupby('gender').mean()['salary']
print(groped)